version: "3"
services:
  mongoservice:
    container_name: mongo_container
    image: mongo
    ports:
      - 27017:27017
    environment:    
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongoservice
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongoservice:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - "mongoservice"
    restart: "always"